apiVersion: v1
kind: Service
metadata:
  namespace: invoice-service
  labels:
    app: invoice-service
  name: invoice-service
spec:
  ports:
  
    - protocol: TCP
      port: 3322
      targetPort: 3322
   
   
  selector:
    app: invoice-service
  type: ClusterIP
